name: deploy to remote

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: gulp build
        uses: actions/setup-node@v1
      - run: yarn install && yarn build
      - name: ssh key generate
        run: echo "$SSH_PRIVATE_KEY" > key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: rsync deploy
        run: rsync -auzrv -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2222" --delete ./Web/* sub.jp-hiroshima-nnn@ssh.lolipop.jp:/home/users/2/sub.jp-hiroshima-nnn/web/site/2021ProN2Q/dev/ --exclude .htaccess
